
### This script reads in individual output files each containing the estimated
### parameters and resulting normalized gene-spot matrices for one cluster/section.
### It then constructs the full gene-spot matrices corresponding to each cluster
### and provides a function to plot the gene counts corresponding to the raw,
### SCTransform-normalized, and spatially normalized (our method) gene spot matrices.

library(here)
library(readr)
library(dplyr)

source(here("Code", "procedure_functions.R"))

## Read in data & clusters
rawcounts <- read_rds(here("Processed Data", "rawcounts.rds"))
ndcounts <- read_rds(here("Processed Data", "ndcounts.rds"))
sctcounts <- read_rds(here("Processed Data", "sctcounts.rds"))
ndclust <- read_csv(here("Processed Data", "nd_constrained_clusters.csv")) %>%
  data.frame() %>% rename(cluster=X0)
real_coords <- read_rds(here("Processed Data", "coords.rds"))
spots <- as.matrix(real_coords)
partition_assignments <- read_rds(here("Processed Data", "partition_assignments.rds"))
features <- read_rds(here("Processed Data", "features.rds"))

output_files <- list.files(path=here("Processed Data", "Estimated Parameters"),
                           pattern="est_params_cluster[0-9]+_section[0-9]+.rds",
                           full.names=TRUE)


extracted_clusters <- sapply(output_files,
                             str_extract, pattern="cluster[0-9]+") %>%
  gsub(pattern="^cluster", replacement="") %>% as.numeric()
extracted_sections <- lapply(output_files, str_extract, pattern="section[0-9]+") %>%
  gsub(pattern="^section", replacement="") %>% as.numeric()

### Read in all the file paths generated by list.files
all_output <- lapply(output_files, read_rds)


section_index_map <- do.call(rbind, lapply(1:length(partition_assignments$unique_sections), function(i) {
  data.frame(
    index=partition_assignments$unique_sections[[i]],
    section=i
  )}))
spots_merge <- spots %>% data.frame() %>% 
  mutate(index=row_number()) %>%
  left_join(section_index_map, by="index") %>% arrange(index)


for (i in 1:length(all_output)) {
  curr_section <- extracted_sections[i]
  all_output[[i]]$cluster <- extracted_clusters[i]
  all_output[[i]]$section <- curr_section
  spot_indices <- which(partition_assignments$overlapping_sections[[curr_section]] %in% partition_assignments$unique_sections[[curr_section]])
  all_output[[i]]$Y_normalized_unique <- all_output[[i]]$Y_normalized[,spot_indices]
  all_output[[i]]$coords_unique <- partition_assignments$unique_coordinates[[curr_section]]
  all_output[[i]]$coords_unique$index <- partition_assignments$unique_sections[[curr_section]]
}



## Put together the g-s matrices for the full map, separately for each gene cluster
all_normalized_matrices <- lapply(unique(extracted_clusters), function(cluster_num) {
  ## Pull out the outputs from the given cluster
  condition <- sapply(all_output, function(output) output$cluster==cluster_num)
  cluster_output <- all_output[condition]
  ## Within the cluster, order by section
  sections <- as.numeric(sapply(cluster_output, "[[", "section"))
  ordered_cluster_output <- cluster_output[order(sections)]
  cluster_coords <- do.call(rbind, lapply(ordered_cluster_output, "[[", "coords_unique"))
  normalized_gs_matrix <- do.call(cbind, lapply(ordered_cluster_output, "[[", "Y_normalized_unique"))
  result <- list(normalized_gs_matrix=normalized_gs_matrix,
                 normalized_coords=cluster_coords,
                 cluster=cluster_num)
  return(result)
})



## Add raw and SCT matrices for each cluster
for (i in 1:length(all_normalized_matrices)) {
  cluster <- all_normalized_matrices[[i]]$cluster
  cluster_indices <- which(ndclust==(cluster-1))
  all_normalized_matrices[[i]]$raw_gs <- rawcounts[cluster_indices,]
  all_normalized_matrices[[i]]$nd_gs <- ndcounts[cluster_indices,]
  all_normalized_matrices[[i]]$sct_gs <- sctcounts[cluster_indices,]
  all_normalized_matrices[[i]]$rawcoords <- spots
}

all_normalized_matrices <- all_normalized_matrices[order(sapply(all_normalized_matrices, "[[", "cluster"))]

clusters <- unique(ndclust$cluster)[order(unique(ndclust$cluster))]
all_cluster_indices <- do.call(c, lapply(clusters, function(cluster) {
  cluster_indices <- which(ndclust==cluster)
}))
# gene_index_map <- data.frame(
#   raw_index = all_cluster_indices,
#   sp_index = c(1:length(all_cluster_indices))
# ) %>%
#   arrange(raw_index)


## Full matrix
## The rows and columns of this are named with the gene and spot barcodes, so when
## you have all of them (for all the genes and sections), can reorder to match the raw, 
## sctransform, and NormalizeData gene spot matrices.
spcounts_unordered <- do.call(rbind, lapply(all_normalized_matrices, "[[", "normalized_gs_matrix"))

## Since this is an example with just a subset of the full g-s matrix, I will just
## output this as is without reordering the rows and columns.
spcounts <- spcounts_unordered


plot_gene_count <- function(gene_name, dot_size=2) {
  gene_name_short <- (features %>% filter(gene_long==gene_name))$gene
  gene_spcounts <- spcounts[which(rownames(spcounts)==gene_name),]
  gene_spdata <- data.frame(
    spot_name=names(gene_spcounts),
    spcount=unname(gene_spcounts)
  )
  coord_data <- real_coords %>% data.frame()
  coord_data$spot_name <- rownames(coord_data)
  
  plot_data <- coord_data %>%
    left_join(gene_spdata, by="spot_name") %>%
    filter(!is.na(spcount))
  count_plot <- ggplot(plot_data, aes(x=x,y=y,color=spcount)) +
    geom_point(size=dot_size) +
    scale_color_viridis_c(option="magma") + 
    theme_classic() +
    theme(axis.text.x=element_blank(), axis.text.y=element_blank(),
          axis.ticks.x=element_blank(), axis.ticks.y=element_blank()) +
    labs(color="Count",
         title=paste0("Spatially Normalized Counts for ", gene_name, " (", gene_name_short, ")"),
         x="",y="")
  return(count_plot)
}

plot_gene_count(rownames(spcounts)[2], dot_size=16)

write_rds(spcounts, file=here("Processed Data", "spcounts.rds"))


